version: '3'
# kernel memory on the host needs to be configured before running
# use: 'sudo sysctl -w vm.max_map_count=2621441'
services:
  swibws:
    build: .
    volumes:
      - ./data:/home/loud/swib18-workshop/data
    ports:
      - "3000:3000"
      - "5601:5601"
      - "9200:9200"
